// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OnlineShop.Api.Data;

#nullable disable

namespace OnlineShop.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825200750_AddOrders")]
    partial class AddOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home & Living"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Men",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Women",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Computers",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Phones",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Laptops",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 9,
                            Name = "Furniture",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Kitchen",
                            ParentCategoryId = 3
                        });
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PersonalNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("VariantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Description = "Soft everyday tee in a regular fit.",
                            ImageUrl = "https://picsum.photos/seed/tee/600/600",
                            Name = "Classic Cotton T-Shirt",
                            Price = 24.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Description = "Stretch chinos suitable for work or weekend.",
                            ImageUrl = "https://picsum.photos/seed/chinos/600/600",
                            Name = "Slim Fit Chinos",
                            Price = 59.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 5,
                            Description = "Lightweight linen dress with a relaxed silhouette.",
                            ImageUrl = "https://picsum.photos/seed/dress/600/600",
                            Name = "Linen Summer Dress",
                            Price = 79.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 5,
                            Description = "Soft open-front cardigan for layering.",
                            ImageUrl = "https://picsum.photos/seed/cardigan/600/600",
                            Name = "Knit Cardigan",
                            Price = 64.50m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 7,
                            Description = "6.5-inch OLED display with dual camera system.",
                            ImageUrl = "https://picsum.photos/seed/phone/600/600",
                            Name = "NovaPhone X",
                            Price = 699.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 7,
                            Description = "Wireless earbuds with active noise cancellation.",
                            ImageUrl = "https://picsum.photos/seed/buds/600/600",
                            Name = "Pulse Buds Pro",
                            Price = 149.00m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 8,
                            Description = "Ultralight 14-inch laptop with all-day battery life.",
                            ImageUrl = "https://picsum.photos/seed/aerobook/600/600",
                            Name = "AeroBook 14",
                            Price = 1099.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            Description = "High-performance laptop for creators and developers.",
                            ImageUrl = "https://picsum.photos/seed/forgepro/600/600",
                            Name = "ForgePro 16",
                            Price = 1599.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            Description = "Solid oak table seating up to six.",
                            ImageUrl = "https://picsum.photos/seed/table/600/600",
                            Name = "Oak Dining Table",
                            Price = 449.00m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 9,
                            Description = "Upholstered armchair with walnut legs.",
                            ImageUrl = "https://picsum.photos/seed/chair/600/600",
                            Name = "Lounge Armchair",
                            Price = 299.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 10,
                            Description = "Non-stick ceramic set with three pans and lids.",
                            ImageUrl = "https://picsum.photos/seed/cookware/600/600",
                            Name = "Ceramic Cookware Set",
                            Price = 129.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 10,
                            Description = "Glass carafe, dripper, and filters for daily brewing.",
                            ImageUrl = "https://picsum.photos/seed/coffee/600/600",
                            Name = "Pour-Over Coffee Kit",
                            Price = 42.00m,
                            StockQuantity = 70
                        });
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Black",
                            ProductId = 1,
                            Size = "S",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 2,
                            Color = "Black",
                            ProductId = 1,
                            Size = "M",
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 3,
                            Color = "Black",
                            ProductId = 1,
                            Size = "L",
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 4,
                            Color = "Black",
                            ProductId = 1,
                            Size = "XL",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 5,
                            Color = "White",
                            ProductId = 1,
                            Size = "M",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 6,
                            Color = "White",
                            ProductId = 1,
                            Size = "L",
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 7,
                            Color = "Sand",
                            ProductId = 3,
                            Size = "S",
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 8,
                            Color = "Sand",
                            ProductId = 3,
                            Size = "M",
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 9,
                            Color = "Sand",
                            ProductId = 3,
                            Size = "L",
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 10,
                            Color = "Navy",
                            ProductId = 3,
                            Size = "M",
                            StockQuantity = 8
                        });
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.Category", b =>
                {
                    b.HasOne("OnlineShop.Api.Entities.Category", "ParentCategory")
                        .WithMany("Children")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.OrderItem", b =>
                {
                    b.HasOne("OnlineShop.Api.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.Product", b =>
                {
                    b.HasOne("OnlineShop.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.ProductVariant", b =>
                {
                    b.HasOne("OnlineShop.Api.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Api.Entities.Product", b =>
                {
                    b.Navigation("Variants");
                });
#pragma warning restore 612, 618
        }
    }
}
